/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavbar";
import TopNav from "@/components/top-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin - Khatra Events",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={cn("min-h-screen w-full bg-white text-black flex ", inter.className,)}>
      <div className={cn("min-h-screen w-full bg-white text-black  ", inter.className)}>
        <div className="p-2 w-full flex ">
          <SideNavbar />
          <div className="w-full">
            <TopNav />
            <div className="w-full p-10">{children}</div>
          </div>
        </div>
      </div>
    </div>
  );
}
